import = [
  # uncomment the flavour you want below:
  # ~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]

    opacity = 0.8

[font]

    normal = { family = "JetBrainsMonoNLNerdFont", style = "Regular" }
    bold= { family = "JetBrainsMonoNLNerdFont", style = "Bold" }
    italic= { family = "JetBrainsMonoNLNerdFont", style = "Italic" }
    bold_italic= { family = "JetBrainsMonoNLNerdFont", style = "Bold Italic" }

    size = 11

